CREATE SCHEMA `FRAMEWORK-SAMPLES`;

CREATE TABLE `SECURITY_USER`
(
    `ID`        varchar(45) COLLATE utf8mb4_bin NOT NULL,
    `ACCOUNT`   varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
    `REAL_NAME` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin